version: "3.3"

services:
  website:
    build:
      context: .
      args:
        SETTINGS_MODULE: online_competitions.settings.test_settings
    ports:
      - "8430:8000"
    volumes:
      - "staticfiles:/app/static"
      - type: "bind"
        source: "./db.sqlite3"
        target: "/app/db.sqlite3"
      - type: "bind"
        source: "./media"
        target: "/app/media"
    restart: always

  static:
    image: "nginx:1.23"
    depends_on:
      - "website"
    ports:
      - "8431:80"
    volumes:
      - "staticfiles:/usr/share/nginx/html:ro"
    restart: always

volumes:
  staticfiles:
