version: "3.3"

services:
  website:
    build:
      context: .
      args:
        SETTINGS_MODULE: online_competitions.settings.test_settings
    ports:
      - "127.0.0.1:8430:8000"
    volumes:
      - "staticfiles:/app/static"
      - type: "bind"
        source: "/data/www/kos-test/db.sqlite3"
        target: "/app/db.sqlite3"
      - type: "bind"
        source: "/data/www/kos-test/media"
        target: "/app/media"
      - type: "bind"
        source: "/data/www/kos-test/.secrets"
        target: "/app/.secrets"
    restart: always

  static:
    image: "nginx:1.25"
    depends_on:
      - "website"
    ports:
      - "127.0.0.1:8431:80"
    volumes:
      - "staticfiles:/usr/share/nginx/html:ro"
    restart: always

volumes:
  staticfiles:
