# Generated by Django 4.0 on 2022-06-12 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('kos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.AddField(
            model_name='puzzle',
            name='location',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='offline_show_delay',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='user',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='pdf_solution',
            field=models.FileField(
                upload_to='', verbose_name='Riešenie v PDF'),
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='kos.team')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='category',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to='kos.category'),
        ),
    ]
