# Generated by Django 4.0 on 2022-06-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kos', '0002_category_puzzle_location_puzzle_offline_show_delay_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'kategória', 'verbose_name_plural': 'kategórie'},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'šifrovačka', 'verbose_name_plural': 'šifrovačky'},
        ),
        migrations.AlterModelOptions(
            name='puzzle',
            options={'verbose_name': 'šifra', 'verbose_name_plural': 'šifry'},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'verbose_name': 'odovzdanie šifry', 'verbose_name_plural': 'odovzdania šifier'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'tím', 'verbose_name_plural': 'tímy'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'verbose_name': 'Člen tímu', 'verbose_name_plural': 'Členovia tímov'},
        ),
        migrations.AddField(
            model_name='puzzle',
            name='name',
            field=models.CharField(default='šifra', max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='current_level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
