# Generated by Django 4.0 on 2022-08-03 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kos', '0004_alter_team_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='unlock_code',
            field=models.CharField(max_length=50, null=True, verbose_name='Kód na odomknutie šifry'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='solution',
            field=models.CharField(max_length=50, verbose_name='Riešenie'),
        ),
    ]
