# Generated by Django 4.0 on 2022-08-04 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kos', '0006_alter_submission_puzzle_alter_submission_submited_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puzzle',
            name='offline_show_delay',
        ),
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Znenie hintu')),
                ('show_after', models.TimeField(verbose_name='Povoliť zobrazenie po')),
                ('hint_penalty', models.TimeField(default=0, verbose_name='Penalta za predošlé hinty')),
                ('count_as_penalty', models.BooleanField(verbose_name='Počíta sa do penalty')),
                ('prerequisites', models.ManyToManyField(to='kos.Hint', verbose_name='Nutné zobrať pred')),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kos.puzzle')),
            ],
            options={
                'verbose_name': 'hint',
                'verbose_name_plural': 'hinty',
            },
        ),
        migrations.AddField(
            model_name='team',
            name='hints_taken',
            field=models.ManyToManyField(to='kos.Hint', verbose_name='Zobraté hinty'),
        ),
    ]
