# Generated by Django 4.0 on 2022-08-09 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kos', '0008_alter_hint_prerequisites_alter_team_hints_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hint',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, to='kos.Hint', verbose_name='Nutné zobrať pred'),
        ),
        migrations.AlterField(
            model_name='team',
            name='hints_taken',
            field=models.ManyToManyField(blank=True, to='kos.Hint', verbose_name='Zobraté hinty'),
        ),
    ]
