# Generated by Django 4.0 on 2022-08-09 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kos', '0010_alter_hint_hint_penalty_alter_hint_show_after'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Verejná hra'),
        ),
    ]
