# Generated by Django 4.0 on 2022-08-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kos', '0012_rename_submited_at_submission_submitted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='pdf_solution',
            field=models.FileField(null=True, upload_to='', verbose_name='Riešenie v PDF'),
        ),
    ]
