# Generated by Django 4.0 on 2022-08-23 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kos', '0013_alter_puzzle_pdf_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='pdf_solution',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Riešenie v PDF'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='kos.team'),
        ),
    ]
