# Generated by Django 4.0 on 2022-08-23 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kos', '0014_alter_puzzle_pdf_solution_alter_teammember_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
