# Generated by Django 4.0 on 2022-08-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kos', '0015_remove_team_category_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Hra je aktívna'),
        ),
    ]
