# Generated by Django 4.0 on 2022-08-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kos', '0016_game_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start', models.DateTimeField(verbose_name='Začiatok hry')),
                ('end', models.DateTimeField(verbose_name='Koniec hry')),
                ('is_public', models.BooleanField(default=True, verbose_name='Verejná hra')),
                ('is_active', models.BooleanField(default=False, verbose_name='Hra je aktívna')),
            ],
            options={
                'verbose_name': 'Ročník',
                'verbose_name_plural': 'Ročníky',
            },
        ),
        migrations.RemoveField(
            model_name='game',
            name='end',
        ),
        migrations.RemoveField(
            model_name='game',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='game',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='game',
            name='start',
        ),
    ]
