# Generated by Django 4.0 on 2022-08-25 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kos', '0016_game_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start', models.DateTimeField(verbose_name='Začiatok hry')),
                ('end', models.DateTimeField(verbose_name='Koniec hry')),
            ],
            options={
                'verbose_name': 'Ročník',
                'verbose_name_plural': 'Ročníky',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kos.year', verbose_name='Ročník'),
        ),
    ]
