# Generated by Django 4.0 on 2022-08-29 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kos', '0017_year_remove_game_end_remove_game_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kos.year', verbose_name='Ročník'),
        ),
    ]
