# Generated by Django 4.0 on 2022-09-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kos', '0019_alter_game_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='final_message',
            field=models.TextField(blank=True, null=True, verbose_name='Správa po ukončení'),
        ),
    ]
