# Generated by Django 4.0 on 2022-09-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kos', '0019_alter_game_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_submitted_as_unlock_code',
            field=models.BooleanField(default=False, verbose_name='Pokus odovzdaný ako vstupný kód'),
        ),
    ]
