# Generated by Django 4.0 on 2022-09-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kos', '0020_game_final_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='year',
            name='solutions_public',
            field=models.BooleanField(default=True, verbose_name='Zverejnené riešenia'),
        ),
    ]
