# Generated by Django 4.0 on 2022-09-06 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kos', '0020_submission_is_submitted_as_unlock_code'),
        ('kos', '0022_alter_year_solutions_public'),
    ]

    operations = [
    ]
