# Generated by Django 4.0 on 2023-07-17 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kos', '0024_game_after_game_message_game_before_game_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
