# Generated by Django 4.0 on 2023-07-20 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kos', '0025_game_price_offline_game_price_online_team_paid'),
        ('kos', '0026_alter_team_user'),
    ]

    operations = [
    ]
