# Generated by Django 4.0 on 2023-08-21 16:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kos', '0027_merge_20230721_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='year',
            name='registration_deadline',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 21, 16, 40, 0, 820558, tzinfo=utc), verbose_name='Registrácia do'),
            preserve_default=False,
        ),
    ]
