# Generated by Django 4.0 on 2023-09-01 09:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kos', '0028_year_registration_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='correct',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='puzzle',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='team',
        ),
        migrations.AddField(
            model_name='puzzle',
            name='skip_allowed_after',
            field=models.DurationField(default=datetime.timedelta(0), help_text='Čas po ktorom je možné preskočiť šifru', verbose_name='Skip'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Tím je verejný'),
        ),
        migrations.AddField(
            model_name='year',
            name='photo_url',
            field=models.TextField(blank=True, null=True, verbose_name='Link na fotogalériu'),
        ),
        migrations.CreateModel(
            name='PuzzleTeamState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skipped', models.BooleanField(default=False, verbose_name='Tím preskočil šifru')),
                ('solved', models.BooleanField(verbose_name='Tím vyriešil šifru')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Začiatok riešenia')),
                ('ended_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Koniec riešenia')),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='kos.puzzle')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='kos.team')),
            ],
            options={
                'verbose_name': 'Stav tímu na šifre',
                'verbose_name_plural': 'Stavy tímov na šifrách',
            },
        ),
    ]
