# Generated by Django 4.0 on 2023-09-04 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kos', '0029_game_frozen_results_json_team_is_public_and_more'),
        ('kos', '0031_submission_correct_submission_puzzle_team_state'),
    ]

    operations = [
    ]
