# Generated by Django 4.0 on 2023-09-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kos', '0033_hint_is_dead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzleteamstate',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Začiatok riešenia'),
        ),
    ]
