# Generated by Django 4.0.3 on 2022-03-07 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mas_problem', '0005_remove_problem_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='is_starting_level_for_grades',
            field=models.ManyToManyField(blank=True, to='mas_problem.grade'),
        ),
        migrations.AlterField(
            model_name='level',
            name='previous_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mas_problem.level'),
        ),
    ]
