# Generated by Django 4.0.3 on 2022-03-07 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mas_problem', '0006_alter_level_is_starting_level_for_grades_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mas_problem.level'),
        ),
    ]
