# Generated by Django 4.0.3 on 2022-03-07 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mas_problem', '0007_problem_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mas_problem.level'),
        ),
    ]
