# Generated by Django 4.0 on 2022-06-11 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mas_problem', '0008_alter_problem_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='current_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mas_problem.level'),
        ),
        migrations.AddField(
            model_name='competitor',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mas_problem.game'),
        ),
        migrations.AlterField(
            model_name='level',
            name='is_starting_level_for_grades',
            field=models.ManyToManyField(blank=True, to='mas_problem.Grade'),
        ),
    ]
