# Generated by Django 4.0 on 2022-08-11 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mas_problem', '0009_competitor_current_level_competitor_game_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='submited_at',
            new_name='submitted_at',
        ),
    ]
